### ISSUE TITLE
1.4 Account / profile modification

### ISSUE THREAD

**Issue by YousefElsendiony** [peterxie/Crank#25]
As an existing user, I would like to be able to change or modify my account settings. This may include changing my password, graduation data, or display name and privacy settings (displaying this data publicly)
Priority:  10

**Comment by ab4359** [comment]
Known issues for password change:
-Can make a password change that doesn't comply with requirements (e.g. "a" is a valid password)

Black box items tested and confirmed working:
• Verifying correct old password
• Verifying new passwords match
