### ISSUE TITLE
1.5 Password reset

### ISSUE THREAD

**Issue by YousefElsendiony** [peterxie/Crank#26]
Change the password reset from a full email address to entering the uni.  Have the same input controls that we will have for uni at signup.
Priority:  40

**Comment by ab4359** [comment]
This may no longer be necessary.  Since this is handled by the framework, there is little additional value in changing this from an email input to a uni input.  The framework is expected to control for malformed inputs in this case.

**Comment by YousefElsendiony** [comment]
Closed as this is already handled well within API and our codebase as per Tony's comment.
