### ISSUE TITLE
1.6 Class entry or selection

### ISSUE THREAD

**Issue by YousefElsendiony** [peterxie/Crank#27]
An existing user should be able to select a class/professor pair from a prepopulated list to rate. - flow: select the class first, and then the professor from a second drop down list
Priority:  20

**Comment by peterxie** [comment]
Looked into this when I first made the rating page and it's a lot more complex than it seems. We'd need to write javascript which updated the drop down upon the selection action since django has no built in support for it

**Comment by YousefElsendiony** [comment]
Technically Unfeasible.
