### ISSUE TITLE
Component code inspection (assignment 6)

### ISSUE THREAD

**Issue by ab4359** [peterxie/Crank#51]
Pick two significant components from your code, one written by each pair, focusing on those components with the most (historically) known problems and/or complexity.  A "component" might be a module, a package, a large class, an interrelated set of smaller classes, etc. Hold a code inspection meeting with all team members present (or participating remotely via screen sharing) and walk through the source code of each component. Try to find additional problems, besides the known problems (do not dwell on problems already found by static analysis). For component A, the reader should be one of members of the pair who developed A and the recorder should be the other member of that pair, and then switch to the other pair for component B. If your team does not have exactly four members, improvise, but the reader and the recorder should not be the same person. (The 2-person team only needs to review one component.)

**Comment by YousefElsendiony** [comment]
Will close when the report is submitted.
